export const mentorActionType = {
  SET_MENTOR: "SET_CURRENT_MENTOR",
  ADD_MENTORSHIP: "ADD_NEW_MENTORSHIP",
  UPDATE_MENTORSHIP: "UPDATE_MENTORSHIP",
  GET_MENTORSHIPS: "GET_MENTORSHIPS",
  SET_MENTORSHIPS: "SET_MENTORSHIPS",
  DELETE_MENTORSHIP: "DELETE_MENTORSHIP",
};
